name: ci-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  pippo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: easingthemes/ssh-deploy@main
        with:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         ARGS: "-rlgoDzvc -i"
         SOURCE: "dist/"
         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         TARGET: ${{ vars.REMOTE_TARGET }}
         EXCLUDE: "/dist/, /node_modules/"
         SCRIPT_BEFORE: |
           whoami
           ls -al
         SCRIPT_AFTER: |
           whoami
           ls -al
           echo $RSYNC_STDOUT
